#!/usr/bin/python3
"""Lance le Centre BinixX OS (accueil, catalogue des logiciels Windows, aide)."""

import sys

sys.path.insert(0, "/usr/lib/binixx/centre")

from binixx_centre.app import main  # noqa: E402

sys.exit(main())
