#!/usr/bin/python3
"""Taille du texte du bureau et des applications : binixx-taille-texte etat | appliquer 100..200 | retablir."""

import sys

sys.path.insert(0, "/usr/lib/binixx/centre")

from binixx_centre.taille_texte import main  # noqa: E402

sys.exit(main())
