#!/usr/bin/python3
"""Place la barre des tâches en haut ou en bas : binixx-barre haut | bas | etat."""

import sys

sys.path.insert(0, "/usr/lib/binixx/centre")

from binixx_centre.barre import main  # noqa: E402

sys.exit(main())
