#!/usr/bin/python3
"""Lance le Centre NicOS (accueil, catalogue des logiciels Windows, aide)."""

import sys

sys.path.insert(0, "/usr/lib/nicos/centre")

from nicos_centre.app import main  # noqa: E402

sys.exit(main())
